Fix Github autoreply script
Fix the following syntax error:

  File "./job/tf-github-autoreply/github_pr_bot.py", line 41
      for issue in repo.get_issues(since=datetime.datetime(2019-2020 10, 17, 12)):
                                                                      ^
  SyntaxError: invalid syntax

Most likely, this got mistakenly included as part of a batch update of
copyright dates by commit 579c737b3b253d7ffd6a1449818e4795ae0b278e.

Change-Id: Ifdf6e2063b90a8d0b32415f2e3c215689c6d4b3c
Signed-off-by: Sandrine Bailleux <sandrine.bailleux@arm.com>